// Rawhide Identity — the seed personas (happy / edge / error scenarios).
// `scenario` + `chips` are presentation hints for the picker UI.
import type { Persona } from "./types.ts";

export const presets: Persona[] = [
  {
    id: "valid",
    source: "preset",
    label: "Valid user",
    description: "Happy path — fully populated",
    scenario: "happy",
    chips: ["sub", "name", "email", "✓ verified"],
    claims: { sub: "user-001", name: "Ada Vaqueira", email: "ada@example.test", email_verified: true },
  },
  {
    id: "admin",
    source: "preset",
    label: "Admin",
    description: "Role-based authorization",
    scenario: "happy",
    chips: ["roles: admin"],
    claims: { sub: "user-002", name: "Admin", email: "admin@example.test", roles: ["admin"] },
  },
  {
    id: "expiring",
    source: "preset",
    label: "Expiring (30s)",
    description: "Exercises the refresh loop",
    scenario: "edge",
    chips: ["TTL 30s", "refreshable"],
    idTokenTTL: 30,
    refreshable: true,
    claims: { sub: "user-003", email: "exp@example.test" },
  },
  {
    id: "long-lived",
    source: "preset",
    label: "Long-lived (24h)",
    description: "Long sessions",
    scenario: "edge",
    chips: ["TTL 24h"],
    idTokenTTL: 86400,
    claims: { sub: "user-004", email: "long@example.test" },
  },
  {
    id: "minimal",
    source: "preset",
    label: "Minimal",
    description: "Missing optional claims",
    scenario: "edge",
    chips: ["sub only"],
    claims: { sub: "user-005" },
  },
  {
    id: "unverified-email",
    source: "preset",
    label: "Unverified email",
    description: "Email-verification gating",
    scenario: "edge",
    chips: ["email_verified: false"],
    claims: { sub: "user-006", email: "unv@example.test", email_verified: false },
  },
  {
    id: "org-member",
    source: "preset",
    label: "Org member",
    description: "Multi-tenant / groups",
    scenario: "edge",
    chips: ["roles: editor", "groups", "org_id"],
    claims: { sub: "user-007", roles: ["editor"], groups: ["acme/eng"], org_id: "acme" },
  },
  {
    id: "new-user",
    source: "preset",
    label: "New user",
    description: "Sparse onboarding profile",
    scenario: "edge",
    chips: ["sub", "email", "no name"],
    claims: { sub: "user-008", email: "new@example.test", updated_at: Math.floor(Date.now() / 1000) },
  },
  {
    id: "expired",
    source: "preset",
    label: "Expired token",
    description: "exp in the past — RP must reject",
    scenario: "error",
    chips: ["exp in past"],
    idTokenTTL: -60,
    claims: { sub: "user-009", email: "expired@example.test" },
  },
  {
    id: "access-denied",
    source: "preset",
    label: "Denies consent",
    description: "Simulates the user cancelling",
    scenario: "error",
    chips: ["error: access_denied"],
    authorizeError: { error: "access_denied", error_description: "user denied" },
    claims: { sub: "user-010" },
  },

  // ---- additional valid users (multi-user dev: 2 per kind) ----
  {
    id: "valid-bea",
    source: "preset",
    label: "Second user (Bea)",
    description: "Another standard user — for multi-user testing",
    scenario: "happy",
    chips: ["sub", "name", "email", "✓ verified"],
    claims: { sub: "user-011", name: "Bea Ranchera", email: "bea@example.test", email_verified: true },
  },
  {
    id: "admin-rae",
    source: "preset",
    label: "Second admin (Rae)",
    description: "Another admin — for multi-admin testing",
    scenario: "happy",
    chips: ["roles: admin"],
    claims: {
      sub: "user-012",
      name: "Rae Holloway",
      email: "rae@example.test",
      email_verified: true,
      roles: ["admin"],
    },
  },
  {
    id: "org-owner",
    source: "preset",
    label: "Org owner",
    description: "Organization owner — full org rights",
    scenario: "happy",
    chips: ["roles: owner", "org_id"],
    claims: {
      sub: "user-013",
      name: "Dana Corral",
      email: "dana@acme.test",
      email_verified: true,
      roles: ["owner", "editor"],
      org_id: "acme",
      groups: ["acme/leadership"],
    },
  },
  {
    id: "org-editor",
    source: "preset",
    label: "Org editor",
    description: "Organization member with edit rights",
    scenario: "happy",
    chips: ["roles: editor", "org_id"],
    claims: {
      sub: "user-014",
      name: "Eli Stockman",
      email: "eli@acme.test",
      email_verified: true,
      roles: ["editor"],
      org_id: "acme",
      groups: ["acme/eng"],
    },
  },

  // ---- additional edge cases ----
  {
    id: "short-token",
    source: "preset",
    label: "Short access token (10s)",
    description: "Access token expires fast — /userinfo 401s after ~10s",
    scenario: "edge",
    chips: ["access TTL 10s"],
    accessTokenTTL: 10,
    claims: { sub: "user-015", name: "Sam Brisco", email: "sam@example.test", email_verified: true },
  },
  {
    id: "i18n",
    source: "preset",
    label: "Unicode profile",
    description: "Non-ASCII name + locale — tests i18n handling",
    scenario: "edge",
    chips: ["unicode name", "locale"],
    claims: {
      sub: "user-016",
      name: "山田 ローレン 🤠",
      email: "lauren@example.test",
      email_verified: true,
      locale: "ja-JP",
      zoneinfo: "Asia/Tokyo",
    },
  },
  {
    id: "multi-role",
    source: "preset",
    label: "Many roles",
    description: "Several roles + groups — tests multi-role authz",
    scenario: "edge",
    chips: ["4 roles", "groups"],
    claims: {
      sub: "user-017",
      name: "Morgan Pike",
      email: "morgan@example.test",
      email_verified: true,
      roles: ["admin", "editor", "billing", "support"],
      groups: ["acme/eng", "acme/ops", "acme/oncall"],
    },
  },
  {
    id: "no-email",
    source: "preset",
    label: "No email",
    description: "Named user with no email claim at all",
    scenario: "edge",
    chips: ["sub", "name", "no email"],
    claims: { sub: "user-018", name: "Pat Stetson" },
  },

  // ---- additional error / failure paths (authorize redirects with an OAuth error) ----
  {
    id: "login-required",
    source: "preset",
    label: "Login required",
    description: "Redirects with login_required — RP should re-auth",
    scenario: "error",
    chips: ["error: login_required"],
    authorizeError: { error: "login_required", error_description: "the user must sign in again" },
    claims: { sub: "user-019" },
  },
  {
    id: "consent-required",
    source: "preset",
    label: "Consent required",
    description: "Redirects with consent_required",
    scenario: "error",
    chips: ["error: consent_required"],
    authorizeError: { error: "consent_required", error_description: "user consent is required" },
    claims: { sub: "user-020" },
  },
  {
    id: "server-error",
    source: "preset",
    label: "Server error",
    description: "Redirects with server_error — IdP failure path",
    scenario: "error",
    chips: ["error: server_error"],
    authorizeError: { error: "server_error", error_description: "the provider hit an unexpected error" },
    claims: { sub: "user-021" },
  },
  {
    id: "invalid-scope",
    source: "preset",
    label: "Invalid scope",
    description: "Redirects with invalid_scope",
    scenario: "error",
    chips: ["error: invalid_scope"],
    authorizeError: { error: "invalid_scope", error_description: "a requested scope is invalid or unknown" },
    claims: { sub: "user-022" },
  },
];

// Default knobs live in ./knobs.ts (re-exported here for convenience / back-compat).
export { defaultKnobs } from "./knobs.ts";
