// Rawhide Identity — the ten seed personas (mirrors the spec).
// `scenario` + `chips` are presentation hints for the picker UI.
import type { Persona } from "./types.ts";

export const presets: Persona[] = [
  {
    id: "valid",
    source: "preset",
    label: "Valid user",
    description: "Happy path — fully populated",
    scenario: "happy",
    chips: ["sub", "name", "email", "✓ verified"],
    claims: { sub: "user-001", name: "Ada Vaqueira", email: "ada@example.test", email_verified: true },
  },
  {
    id: "admin",
    source: "preset",
    label: "Admin",
    description: "Role-based authorization",
    scenario: "happy",
    chips: ["roles: admin"],
    claims: { sub: "user-002", name: "Admin", email: "admin@example.test", roles: ["admin"] },
  },
  {
    id: "expiring",
    source: "preset",
    label: "Expiring (30s)",
    description: "Exercises the refresh loop",
    scenario: "edge",
    chips: ["TTL 30s", "refreshable"],
    idTokenTTL: 30,
    refreshable: true,
    claims: { sub: "user-003", email: "exp@example.test" },
  },
  {
    id: "long-lived",
    source: "preset",
    label: "Long-lived (24h)",
    description: "Long sessions",
    scenario: "edge",
    chips: ["TTL 24h"],
    idTokenTTL: 86400,
    claims: { sub: "user-004", email: "long@example.test" },
  },
  {
    id: "minimal",
    source: "preset",
    label: "Minimal",
    description: "Missing optional claims",
    scenario: "edge",
    chips: ["sub only"],
    claims: { sub: "user-005" },
  },
  {
    id: "unverified-email",
    source: "preset",
    label: "Unverified email",
    description: "Email-verification gating",
    scenario: "edge",
    chips: ["email_verified: false"],
    claims: { sub: "user-006", email: "unv@example.test", email_verified: false },
  },
  {
    id: "org-member",
    source: "preset",
    label: "Org member",
    description: "Multi-tenant / groups",
    scenario: "edge",
    chips: ["roles: editor", "groups", "org_id"],
    claims: { sub: "user-007", roles: ["editor"], groups: ["acme/eng"], org_id: "acme" },
  },
  {
    id: "new-user",
    source: "preset",
    label: "New user",
    description: "Sparse onboarding profile",
    scenario: "edge",
    chips: ["sub", "email", "no name"],
    claims: { sub: "user-008", email: "new@example.test", updated_at: Math.floor(Date.now() / 1000) },
  },
  {
    id: "expired",
    source: "preset",
    label: "Expired token",
    description: "exp in the past — RP must reject",
    scenario: "error",
    chips: ["exp in past"],
    idTokenTTL: -60,
    claims: { sub: "user-009", email: "expired@example.test" },
  },
  {
    id: "access-denied",
    source: "preset",
    label: "Denies consent",
    description: "Simulates the user cancelling",
    scenario: "error",
    chips: ["error: access_denied"],
    authorizeError: { error: "access_denied", error_description: "user denied" },
    claims: { sub: "user-010" },
  },
];

// Default knobs live in ./knobs.ts (re-exported here for convenience / back-compat).
export { defaultKnobs } from "./knobs.ts";
